(val rxv01 unit)
(begin (set rxv01 (withXV: ReverseXVector xv01)) (add: xvs rxv01) (add: ns 'rxv01) unit)
(val rxv02 unit)
(begin (set rxv02 (withXV: ReverseXVector xv02)) (add: xvs rxv02) (add: ns 'rxv02) unit)
(val rxv03 unit)
(begin (set rxv03 (withXV: ReverseXVector xv03)) (add: xvs rxv03) (add: ns 'rxv03) unit)
(val rxv04 unit)
(begin (set rxv04 (withXV: ReverseXVector xv04)) (add: xvs rxv04) (add: ns 'rxv04) unit)
(val rxv05 unit)
(begin (set rxv05 (withXV: ReverseXVector xv07)) (add: xvs rxv05) (add: ns 'rxv05) unit)
