(test-debug (xv:name:-no-init XVectorTester rxv01 'rxv01))
(test-debug (xv:name:-no-init XVectorTester rxv02 'rxv02))
(test-debug (xv:name:-no-init XVectorTester rxv03 'rxv03))
(test-debug (xv:name:-no-init XVectorTester rxv04 'rxv04))
(test-debug (xv:name:-no-init XVectorTester rxv05 'rxv05))
